apiVersion: v1
kind: Pod
metadata:
  name: mysql-employee
  labels:
     app: mysql
spec:
  containers:
    - name: mysql
      image: 466548522055.dkr.ecr.us-east-1.amazonaws.com/ass02-db:v1.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
      ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP