apiVersion: v1
kind: Pod
metadata:
  name: employees-webapp
  namespace: app
  labels:
    app: employees
spec:
  containers:
    - name: employees-webapp
      image: 466548522055.dkr.ecr.us-east-1.amazonaws.com/ass02-app:v1.0
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP