apiVersion: v1
kind: Service
metadata:
  name: mysql-employee
  labels:
    name: mysql-employee
    app: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: mysql-employee
    app: mysql