apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    app: employees
---
apiVersion: v1
kind: Service
metadata:
  name: employee-webapp
  namespace: app
  labels:
    app: employees
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app: employees